# Generated by Django 4.2.24 on 2025-09-16 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "geojson_file",
                    models.CharField(
                        blank=True,
                        help_text="relative path under static/geojson or filename",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WarningEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("horizon", models.PositiveSmallIntegerField(default=1)),
                ("phenomenon", models.CharField(max_length=64)),
                ("severity", models.CharField(blank=True, max_length=32, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.district"
                    ),
                ),
            ],
            options={
                "unique_together": {("district", "date", "horizon", "phenomenon")},
            },
        ),
        migrations.CreateModel(
            name="VerificationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date or period end the metric refers to"
                    ),
                ),
                ("horizon", models.PositiveSmallIntegerField(default=1)),
                ("metric", models.CharField(max_length=64)),
                ("value", models.FloatField()),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.district",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "horizon", "metric"],
                        name="core_verifi_date_03346d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RealizedEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date the forecast is for (YYYY-MM-DD)"),
                ),
                (
                    "horizon",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Forecast horizon in days (1..7)"
                    ),
                ),
                ("rainfall_mm", models.FloatField(blank=True, null=True)),
                (
                    "rainfall_category",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("extras", models.JSONField(blank=True, default=dict)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="core.district",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Realized Entry",
                "abstract": False,
                "unique_together": {("district", "date", "horizon")},
            },
        ),
        migrations.CreateModel(
            name="ForecastEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date the forecast is for (YYYY-MM-DD)"),
                ),
                (
                    "horizon",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Forecast horizon in days (1..7)"
                    ),
                ),
                ("rainfall_mm", models.FloatField(blank=True, null=True)),
                (
                    "rainfall_category",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("extras", models.JSONField(blank=True, default=dict)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="manual", max_length=32)),
                ("version", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="core.district",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Entry",
                "abstract": False,
                "unique_together": {("district", "date", "horizon")},
            },
        ),
    ]
