# Generated by Django 4.2.24 on 2025-09-20 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Forecast valid date (one row per date).', unique=True)),
                ('scope', models.CharField(choices=[('district', 'District-level'), ('state', 'State-level'), ('mixed', 'Mixed (district+states)')], default='mixed', max_length=16)),
                ('data', models.JSONField(default=dict, help_text='Map of area_id -> {category, rainfall_mm, ...}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Map Forecast',
                'verbose_name_plural': 'Map Forecasts',
                'ordering': ['-date'],
            },
        ),
    ]
